### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by MichaelCong** [songwsx/RFSong-7993#1]
python train_RFB.py 
Loading Dataset...
Traceback (most recent call last):
  File "train_RFB.py", line 166, in <module>
    train()
  File "train_RFB.py", line 88, in train
    dataset = VOCDetection(VOCroot, train_sets, preproc(img_dim, rgb_means, p), AnnotationTransform())
  File "/home/rencong/RFBNET/SSD-YOLO/data/voc0712.py", line 120, in __init__
    img_id, value = line.split()
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by songwsx** [comment]
云深不知处-目标检测 763679865 在群里问吧


------------------ 原始邮件 ------------------
发件人: "任聪"<notifications@github.com>;
发送时间: 2019年9月6日(星期五) 晚上8:56
收件人: "songwsx/RFSong-7993"<RFSong-7993@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [songwsx/RFSong-7993] ValueError: not enough values to unpack(expected 2, got 1) (#1)




python train_RFB.py
 Loading Dataset...
 Traceback (most recent call last):
 File "train_RFB.py", line 166, in 
 train()
 File "train_RFB.py", line 88, in train
 dataset = VOCDetection(VOCroot, train_sets, preproc(img_dim, rgb_means, p), AnnotationTransform())
 File "/home/rencong/RFBNET/SSD-YOLO/data/voc0712.py", line 120, in init
 img_id, value = line.split()
 ValueError: not enough values to unpack (expected 2, got 1)
